# Generated by Django 3.2.13 on 2022-07-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistacontratocpf',
            name='cadastro_completo',
            field=models.BooleanField(default=False),
        ),
    ]
