# Generated by Django 3.2.13 on 2022-07-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistaContratoEmpresario',
            fields=[
                ('artistacontratocnpj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mapeamento_cultural.artistacontratocnpj')),
                ('documento_empresario_exclusivo', models.FileField(upload_to='documento_empresario_exclusivo', verbose_name="Documento que comprove que o prestador é exclusivo do 'fazedor de cultura' em questão.*:")),
            ],
            bases=('mapeamento_cultural.artistacontratocnpj',),
        ),
        migrations.AddField(
            model_name='artistacontratocpf',
            name='fazedor_cultura',
            field=models.CharField(default='Eduardo Salarini', max_length=100, verbose_name='Nome artístico do Fazedor de Cultura:'),
            preserve_default=False,
        ),
    ]
