# Generated by Django 3.2.13 on 2022-07-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='email',
        ),
    ]
