# Generated by Django 3.2.13 on 2022-06-30 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistacontrato',
            name='tipo_contratacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapeamento_cultural.tiposcontratação', verbose_name='Tipo de contratação:'),
        ),
    ]
