# Generated by Django 3.2.13 on 2022-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0002_auto_20220701_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Atuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Enquadramento_Atuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquadramento', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Forma_insercao_Atuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Publico_Atuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publico', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='artistacontratocpf',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição resumida da atividade artística/culturais desenvolvidas:'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InformacoesExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('cnpj_e', 'CNPJ_Empresario')], max_length=6)),
                ('id_artista', models.CharField(max_length=20)),
                ('qnt', models.CharField(choices=[('0', '0 a 10'), ('1', '11 a 20'), ('2', '21 a 30'), ('3', '31 a 40'), ('4', '41 a 50'), ('5', 'Mais de 50')], max_length=1)),
                ('status', models.CharField(choices=[('p', 'Principal (maior fonte de renda/profissão)'), ('s', 'secundaria (renda extra, ou prática sem fins lucrativos como lazer)')], max_length=1)),
                ('instagram', models.CharField(blank=True, max_length=150)),
                ('facebook', models.CharField(blank=True, max_length=150)),
                ('youtube', models.CharField(blank=True, max_length=150)),
                ('area', models.ManyToManyField(to='mapeamento_cultural.Area_Atuacao')),
                ('enquadramento', models.ManyToManyField(to='mapeamento_cultural.Enquadramento_Atuacao')),
                ('forma_atuacao', models.ManyToManyField(to='mapeamento_cultural.Forma_insercao_Atuacao')),
                ('publico', models.ManyToManyField(to='mapeamento_cultural.Publico_Atuacao')),
            ],
        ),
    ]
