# Generated by Django 3.2.13 on 2022-07-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0002_artistacontratocpf_cadastro_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesextras',
            name='tipo',
            field=models.CharField(choices=[('1', 'CPF'), ('2', 'CNPJ')], max_length=1),
        ),
    ]
