# Generated by Django 3.1.4 on 2022-09-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0003_auto_20220915_1520'),
        ('mapeamento_cultural', '0002_auto_20220825_1123'),
    ]

    operations = [
    ]
