# Generated by Django 3.2.13 on 2022-07-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0003_alter_informacoesextras_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistacontratocpf',
            name='data_nascimento',
            field=models.DateTimeField(null=True, verbose_name='Data Nascimento'),
        ),
    ]
