# Generated by Django 3.2.13 on 2022-07-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0003_alter_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesextras',
            name='area',
        ),
        migrations.AlterField(
            model_name='artista',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, to='mapeamento_cultural.Area_Atuacao', verbose_name='Área(s) de atuação'),
        ),
    ]
