# Generated by Django 3.2.13 on 2022-07-15 22:08

from django.db import migrations, models
import django.db.models.deletion
import mapeamento_cultural.validations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0004_alter_artistacontratocpf_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fazedor_cultura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome artístico:')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, validators=[mapeamento_cultural.validations.validate_CPF], verbose_name='CPF:')),
                ('data_nascimento', models.DateTimeField(null=True, verbose_name='Data Nascimento')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição resumida da atividade artística/culturais desenvolvidas:')),
                ('file_cpf', models.FileField(blank=True, null=True, upload_to='file_cpf', verbose_name='CPF - Documento scaneado:')),
                ('file_comprovante_residencia', models.FileField(blank=True, null=True, upload_to='file_comprovantes_residencia', verbose_name='Comprovante de residência - Documento scaneado:')),
                ('pis', models.CharField(blank=True, max_length=80, null=True, verbose_name='PIS/PASEP/NIT')),
                ('file_pis', models.FileField(blank=True, null=True, upload_to='file_pis', verbose_name='PIS/PASEP/NIT - Documento scaneado:')),
                ('banco', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Banco (Conta Corrente):')),
                ('agencia', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Agência:')),
                ('n_conta', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Número da conta')),
                ('comprovante_de_cc', models.FileField(blank=True, null=True, upload_to='file_comprovante_cc', verbose_name='Comprovante de número de conta corrente (banco, agência e nº da conta):')),
                ('declaracao_n_viculo', models.FileField(blank=True, null=True, upload_to='file_declaracao_n_vinculo', verbose_name='Declaração de não vínculo com a Administração Federal, Estadual e Municipal:')),
                ('comprovante_iss', models.FileField(blank=True, null=True, upload_to='file_comprovante_iss', verbose_name='Comprovante de inscrição do ISS Municipal:')),
                ('comprovante_recibos', models.FileField(blank=True, null=True, upload_to='file_comprovante_recibos', verbose_name='Recibos, contratos ou notas que comprovem cachê:')),
                ('cadastro_completo', models.BooleanField(default=False)),
                ('fazedor_cultura_cnpj', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome fantasia:')),
                ('cnpj', models.CharField(max_length=11, verbose_name='CNPJ:')),
                ('cpf_responsavel', models.CharField(blank=True, max_length=14, null=True, validators=[mapeamento_cultural.validations.validate_CPF], verbose_name='CPF do responsável:')),
                ('file_cnpj', models.FileField(upload_to='file_cnpj', verbose_name='CNPJ - Documento scaneado evidenciando cadastro em atividades da àrea cultural:')),
                ('prova_inscricao_PJ_nacional', models.FileField(upload_to='prova_inscricao_PJ_nacional', verbose_name='Prova de inscrição no Cadastro Nacional de Pessoa Jurídica:')),
                ('certidao_negativa_debitos_relativos', models.FileField(upload_to='certidao_negativa_debitos_relativos', verbose_name='Certidão Negativa de Débitos Relativos a TRibunais Federais e à Divida Ativa da União:')),
                ('certidao_regularidade_icms', models.FileField(upload_to='certidao_regularidade_icms', verbose_name='Certidão de Regularidade de Tribunais Estaduais (ICMS):')),
                ('certidao_regularidade_iss', models.FileField(upload_to='certidao_regularidade_iss', verbose_name='Certidão de Regularidade de Tribunais Municipais (ISS):')),
                ('certidao_negativa_debitos', models.FileField(upload_to='certidao_negativa_debitos', verbose_name='Certidão Negativa de Débitos:')),
                ('certidao_regularidade_situacao', models.FileField(upload_to='certidao_de_regularidade_de_situacao', verbose_name='Certidão de REgularidade de Situação:')),
                ('certidao_negativa_debitos_trabalhistas', models.FileField(upload_to='certidao_debitos_trabalhistas_cndt', verbose_name='Certidão de Negativa de Débitos Trabalhistas - CDNT:')),
                ('documento_empresario_exclusivo', models.FileField(upload_to='documento_empresario_exclusivo', verbose_name="Documento que comprove que o prestador é exclusivo do 'fazedor de cultura' em questão.*:")),
                ('area', models.ManyToManyField(to='mapeamento_cultural.Area_Atuacao', verbose_name='Area de atuação')),
                ('tipo_contratacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapeamento_cultural.tiposcontratação', verbose_name='Tipo de contratação:')),
            ],
        ),
        migrations.RemoveField(
            model_name='artistacontratocpf',
            name='area',
        ),
        migrations.RemoveField(
            model_name='artistacontratocpf',
            name='tipo_contratacao',
        ),
        migrations.RemoveField(
            model_name='artistacontratocpf',
            name='user_responsavel',
        ),
        migrations.RemoveField(
            model_name='artistacontratoempresario',
            name='artistacontratocnpj_ptr',
        ),
        migrations.DeleteModel(
            name='ArtistaContratoCNPJ',
        ),
        migrations.DeleteModel(
            name='ArtistaContratoCPF',
        ),
        migrations.DeleteModel(
            name='ArtistaContratoEmpresario',
        ),
    ]
