# Generated by Django 3.2.13 on 2022-07-29 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapeamento_cultural', '0004_auto_20220728_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='user_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
