# Generated by Django 3.2.13 on 2022-07-15 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapeamento_cultural', '0005_auto_20220715_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dt. Inclusão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='user_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
