# Generated by Django 3.2.13 on 2022-07-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0005_alter_artista_user_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='descricao',
        ),
        migrations.AddField(
            model_name='informacoesextras',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição resumida da atividade artística/culturais desenvolvidas'),
        ),
    ]
