# Generated by Django 3.2.13 on 2022-07-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0006_auto_20220729_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='cpf_responsavel',
        ),
    ]
