# Generated by Django 3.2.13 on 2022-07-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0006_auto_20220715_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesextras',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artista',
            name='certidao_negativa_debitos_relativos',
            field=models.FileField(blank=True, null=True, upload_to='certidao_negativa_debitos_relativos', verbose_name='Certidão Negativa de Débitos Relativos a TRibunais Federais e à Divida Ativa da União:'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='certidao_negativa_debitos_trabalhistas',
            field=models.FileField(blank=True, null=True, upload_to='certidao_debitos_trabalhistas_cndt', verbose_name='Certidão de Negativa de Débitos Trabalhistas - CDNT:'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='certidao_regularidade_icms',
            field=models.FileField(blank=True, null=True, upload_to='certidao_regularidade_icms', verbose_name='Certidão de Regularidade de Tribunais Estaduais (ICMS):'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='certidao_regularidade_iss',
            field=models.FileField(blank=True, null=True, upload_to='certidao_regularidade_iss', verbose_name='Certidão de Regularidade de Tribunais Municipais (ISS):'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='certidao_regularidade_situacao',
            field=models.FileField(blank=True, null=True, upload_to='certidao_de_regularidade_de_situacao', verbose_name='Certidão de REgularidade de Situação:'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='documento_empresario_exclusivo',
            field=models.FileField(blank=True, null=True, upload_to='documento_empresario_exclusivo', verbose_name="Documento que comprove que o prestador é exclusivo do 'fazedor de cultura' em questão.*:"),
        ),
        migrations.AlterField(
            model_name='artista',
            name='file_cnpj',
            field=models.FileField(blank=True, null=True, upload_to='file_cnpj', verbose_name='CNPJ - Documento scaneado evidenciando cadastro em atividades da àrea cultural:'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='prova_inscricao_PJ_nacional',
            field=models.FileField(blank=True, null=True, upload_to='prova_inscricao_PJ_nacional', verbose_name='Prova de inscrição no Cadastro Nacional de Pessoa Jurídica:'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='area',
            field=models.ManyToManyField(blank=True, to='mapeamento_cultural.Area_Atuacao'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='enquadramento',
            field=models.ManyToManyField(blank=True, to='mapeamento_cultural.Enquadramento_Atuacao'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='forma_atuacao',
            field=models.ManyToManyField(blank=True, to='mapeamento_cultural.Forma_insercao_Atuacao'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='id_artista',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='publico',
            field=models.ManyToManyField(blank=True, to='mapeamento_cultural.Publico_Atuacao'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='qnt',
            field=models.CharField(blank=True, choices=[('0', '0 a 10'), ('1', '11 a 20'), ('2', '21 a 30'), ('3', '31 a 40'), ('4', '41 a 50'), ('5', 'Mais de 50')], max_length=1),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Principal (maior fonte de renda/profissão)'), ('s', 'secundaria (renda extra, ou prática sem fins lucrativos como lazer)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='tipo',
            field=models.CharField(blank=True, choices=[('1', 'CPF'), ('2', 'CNPJ')], max_length=1),
        ),
    ]
