# Generated by Django 3.2.15 on 2022-09-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0007_auto_20220922_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='certidao_negativa_debitos_relativos_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da Certidão Negativa de Débitos Relativos a Tribunais Federais e à Divida Ativa da União'),
        ),
        migrations.AddField(
            model_name='artista',
            name='certidao_negativa_debitos_trabalhistas_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da Certidão de Negativa de Débitos Trabalhistas - CDNT'),
        ),
        migrations.AddField(
            model_name='artista',
            name='certidao_negativa_debitos_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da Certidão Negativa de Débitos'),
        ),
        migrations.AddField(
            model_name='artista',
            name='certidao_regularidade_icms_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da Certidão de Regularidade de Tribunais Estaduais (ICMS)'),
        ),
        migrations.AddField(
            model_name='artista',
            name='certidao_regularidade_iss_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da Certidão de Regularidade de Tribunais Municipais (ISS)'),
        ),
        migrations.AddField(
            model_name='artista',
            name='certidao_regularidade_situacao_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da Certidão de REgularidade de Situação'),
        ),
        migrations.AddField(
            model_name='artista',
            name='documento_empresario_exclusivo_validade',
            field=models.DateField(blank=True, null=True, verbose_name="Validade do Documento que comprove que o prestador é exclusivo do 'fazedor de cultura' em questão.*"),
        ),
        migrations.AddField(
            model_name='artista',
            name='prova_inscricao_PJ_nacional_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Prova de inscrição no Cadastro Nacional de Pessoa Jurídica'),
        ),
    ]
