# Generated by Django 3.2.13 on 2022-07-29 18:59

from django.db import migrations, models
import mapeamento_cultural.validations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0007_remove_artista_cpf_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='telefone',
            field=models.CharField(max_length=15, validators=[mapeamento_cultural.validations.validate_TELEFONE]),
        ),
    ]
