# Generated by Django 3.2.13 on 2022-07-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0007_auto_20220718_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesextras',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='artista',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ:'),
        ),
    ]
