# Generated by Django 3.2.13 on 2022-08-01 18:03

from django.db import migrations, models
import mapeamento_cultural.validations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0008_alter_artista_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='cnpj',
            field=models.CharField(max_length=18, null=True, unique=True, validators=[mapeamento_cultural.validations.validate_CNPJ], verbose_name='CNPJ'),
        ),
    ]
