# Generated by Django 3.2.13 on 2022-07-19 12:49

from django.db import migrations, models
import django.db.models.deletion
import mapeamento_cultural.validations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0008_auto_20220718_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesextras',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='area',
            field=models.ManyToManyField(to='mapeamento_cultural.Area_Atuacao', verbose_name='Principal área de atuação'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='certidao_negativa_debitos',
            field=models.FileField(upload_to='certidao_negativa_debitos', verbose_name='Certidão Negativa de Débitos'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='certidao_negativa_debitos_relativos',
            field=models.FileField(blank=True, null=True, upload_to='certidao_negativa_debitos_relativos', verbose_name='Certidão Negativa de Débitos Relativos a Tribunais Federais e à Divida Ativa da União'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='certidao_negativa_debitos_trabalhistas',
            field=models.FileField(blank=True, null=True, upload_to='certidao_debitos_trabalhistas_cndt', verbose_name='Certidão de Negativa de Débitos Trabalhistas - CDNT'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='certidao_regularidade_icms',
            field=models.FileField(blank=True, null=True, upload_to='certidao_regularidade_icms', verbose_name='Certidão de Regularidade de Tribunais Estaduais (ICMS)'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='certidao_regularidade_iss',
            field=models.FileField(blank=True, null=True, upload_to='certidao_regularidade_iss', verbose_name='Certidão de Regularidade de Tribunais Municipais (ISS)'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='certidao_regularidade_situacao',
            field=models.FileField(blank=True, null=True, upload_to='certidao_de_regularidade_de_situacao', verbose_name='Certidão de REgularidade de Situação'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='comprovante_de_cc',
            field=models.FileField(blank=True, null=True, upload_to='file_comprovante_cc', verbose_name='Comprovante de número de conta corrente (banco, agência e nº da conta)'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='comprovante_iss',
            field=models.FileField(blank=True, null=True, upload_to='file_comprovante_iss', verbose_name='Comprovante de inscrição do ISS Municipal'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='comprovante_recibos',
            field=models.FileField(blank=True, null=True, upload_to='file_comprovante_recibos', verbose_name='Recibos, contratos ou notas que comprovem cachê'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[mapeamento_cultural.validations.validate_CPF], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[mapeamento_cultural.validations.validate_CPF], verbose_name='CPF do responsável'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='declaracao_n_viculo',
            field=models.FileField(blank=True, null=True, upload_to='file_declaracao_n_vinculo', verbose_name='Declaração de não vínculo com a Administração Federal, Estadual e Municipal'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição resumida da atividade artística/culturais desenvolvidas'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='documento_empresario_exclusivo',
            field=models.FileField(blank=True, null=True, upload_to='documento_empresario_exclusivo', verbose_name="Documento que comprove que o prestador é exclusivo do 'fazedor de cultura' em questão.*"),
        ),
        migrations.AlterField(
            model_name='artista',
            name='fazedor_cultura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome artístico'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='fazedor_cultura_cnpj',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='file_cnpj',
            field=models.FileField(blank=True, null=True, upload_to='file_cnpj', verbose_name='CNPJ - Documento scaneado evidenciando cadastro em atividades da àrea cultural'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='file_comprovante_residencia',
            field=models.FileField(blank=True, null=True, upload_to='file_comprovantes_residencia', verbose_name='Comprovante de residência'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='file_cpf',
            field=models.FileField(blank=True, null=True, upload_to='file_cpf', verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='file_pis',
            field=models.FileField(blank=True, null=True, upload_to='file_pis', verbose_name='PIS/PASEP/NIT'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='prova_inscricao_PJ_nacional',
            field=models.FileField(blank=True, null=True, upload_to='prova_inscricao_PJ_nacional', verbose_name='Prova de inscrição no Cadastro Nacional de Pessoa Jurídica'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='tipo_contratacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapeamento_cultural.tiposcontratação', verbose_name='Tipo de contratação'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Principal (maior fonte de renda/profissão)'), ('s', 'Secundaria (renda extra, ou prática sem fins lucrativos como lazer)')], max_length=1),
        ),
    ]
