# Generated by Django 3.2.15 on 2022-09-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0008_auto_20220927_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='prova_inscricao_PJ_nacional_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da Prova de inscrição no Cadastro Nacional de Pessoa Jurídica'),
        ),
    ]
