# Generated by Django 3.2.13 on 2022-07-19 13:18

from django.db import migrations, models
import mapeamento_cultural.validations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0009_auto_20220719_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[mapeamento_cultural.validations.validate_CNPJ], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='area',
            field=models.ManyToManyField(blank=True, to='mapeamento_cultural.Area_Atuacao', verbose_name='Áreas culturais de atuação'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='enquadramento',
            field=models.ManyToManyField(blank=True, to='mapeamento_cultural.Enquadramento_Atuacao', verbose_name='Enquadramento da instituição/entidade/coletivo/grupo'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='forma_atuacao',
            field=models.ManyToManyField(blank=True, to='mapeamento_cultural.Forma_insercao_Atuacao', verbose_name='Formar de inserção da atividade artístico-cultural'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='publico',
            field=models.ManyToManyField(blank=True, to='mapeamento_cultural.Publico_Atuacao', verbose_name='Públicos que participam das ações'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='qnt',
            field=models.CharField(blank=True, choices=[('0', '0 a 10'), ('1', '11 a 20'), ('2', '21 a 30'), ('3', '31 a 40'), ('4', '41 a 50'), ('5', 'Mais de 50')], max_length=1, verbose_name='Quantidade de pessoas que fazem parte da instituição'),
        ),
        migrations.AlterField(
            model_name='informacoesextras',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Principal (maior fonte de renda/profissão)'), ('s', 'Secundaria (renda extra, ou prática sem fins lucrativos como lazer)')], max_length=1, verbose_name='Status da atividade'),
        ),
    ]
