# Generated by Django 3.2.13 on 2022-08-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0009_alter_artista_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(default='Centro', max_length=40, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(max_length=40, verbose_name='Endereço'),
        ),
    ]
