# Generated by Django 3.1.4 on 2022-09-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0009_alter_artista_prova_inscricao_pj_nacional_validade'),
        ('mapeamento_cultural', '0004_merge_20220919_1438'),
    ]

    operations = [
    ]
