# Generated by Django 3.2.13 on 2022-07-19 13:22

from django.db import migrations, models
import mapeamento_cultural.validations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0010_auto_20220719_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='cnpj',
            field=models.CharField(max_length=18, null=True, validators=[mapeamento_cultural.validations.validate_CNPJ], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='cpf',
            field=models.CharField(max_length=14, null=True, validators=[mapeamento_cultural.validations.validate_CPF], verbose_name='CPF'),
        ),
    ]
