# Generated by Django 3.2.15 on 2023-06-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0010_auto_20230206_1140'),
        ('mapeamento_cultural', '0010_merge_20220927_1627'),
    ]

    operations = [
    ]
