# Generated by Django 3.2.13 on 2022-08-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0010_auto_20220801_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprovante_recibos', models.FileField(blank=True, null=True, upload_to='file_comprovante_recibos', verbose_name='Recibos, contratos ou notas que comprovem cachê')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(max_length=40, verbose_name='Bairro:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(max_length=40, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='comprovante_recibos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapeamento_cultural.recibos', verbose_name='Comprovante de recibos'),
        ),
    ]
