# Generated by Django 3.2.13 on 2022-08-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0011_auto_20220811_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibos',
            old_name='comprovante_recibos',
            new_name='comprovante',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='comprovante_recibos',
        ),
        migrations.AddField(
            model_name='recibos',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapeamento_cultural.artista', verbose_name='Artista'),
        ),
    ]
