# Generated by Django 3.2.13 on 2022-08-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0012_auto_20220811_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesextras',
            name='qnt',
            field=models.CharField(blank=True, choices=[('0', '0 a 10'), ('1', '11 a 20'), ('2', '21 a 30'), ('3', '31 a 40'), ('4', '41 a 50'), ('5', 'Mais de 50')], max_length=1, null=True, verbose_name='Quantidade de pessoas que fazem parte da instituição'),
        ),
    ]
