# Generated by Django 3.2.13 on 2022-08-15 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapeamento_cultural', '0012_auto_20220811_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesextras',
            name='qnt',
            field=models.CharField(blank=True, choices=[('0', '0 a 10'), ('1', '11 a 20'), ('2', '21 a 30'), ('3', '31 a 40'), ('4', '41 a 50'), ('5', 'Mais de 50')], max_length=1, verbose_name='Quantidade de pessoas que fazem parte do grupo'),
        ),
        migrations.CreateModel(
            name='Log_anexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.CharField(max_length=150, verbose_name='Anexo')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('dt_alteration', models.DateTimeField(auto_now=True, verbose_name='Dt. Alteração')),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapeamento_cultural.artista', verbose_name='Artista')),
                ('user_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
