# Generated by Django 3.2.13 on 2022-08-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0013_auto_20220815_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_anexos',
            old_name='id_artista',
            new_name='artista',
        ),
    ]
