# Generated by Django 3.2.13 on 2022-08-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeamento_cultural', '0013_alter_informacoesextras_qnt'),
        ('mapeamento_cultural', '0015_log_anexos_filename'),
    ]

    operations = [
    ]
